spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:h2:mem:testDb
    username: sa
    password: password
  h2:
    console:
      enabled: true

debug: true
logging:
  level:
    root: DEBUG