name: Java CI

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:14.6
        env:
          POSTGRES_USER: myuser
          POSTGRES_PASSWORD: mypassword
          POSTGRES_DB: mydatabase
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
      - uses: gradle/gradle-build-action@v2
        with:
          arguments: build
          gradle-version: 8.5
        env:
          JDBC_DATABASE_URL: jdbc:postgresql://localhost:5432/mydatabase
          USERNAME: myuser
          PASSWORD: mypassword
          SPRING_PROFILES_ACTIVE: prod